name: Deploy Frontend to EC2

on:
  push:
    branches:
      - master  # or main if that's your default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/Bank-frontend
            git pull origin master
            npm install
            npm run build
            pm2 delete frontend || true
            pm2 serve dist 80 --name frontend --spa
          EOF
